Repository avidraghav/MyNotes, pull requests merged in 2022-10, with the labels that each got.

#52 added undo functionality-re
  app/src/main/java/com/raghav/mynotes/ui/AllTasksFragment.kt
  app/src/main/java/com/raghav/mynotes/utils/SnackBarUtils.kt
Labels: HACKTOBERFEST-ACCEPTED

#62 NoteApp : Upgraded older dependency
  app/build.gradle
  app/src/main/AndroidManifest.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: HACKTOBERFEST-ACCEPTED

#67 NoteApp : Modified TaskEntity.kt from Serializable to Parcelable
  app/build.gradle
  app/src/main/java/com/raghav/mynotes/models/TaskEntity.kt
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#73 Improved the UX of the 'AddTask' fragment.
  app/src/main/java/com/raghav/mynotes/ui/AddTaskFragment.kt
  app/src/main/res/layout/fragment_add_task.xml
Labels: good first issue, HACKTOBERFEST-ACCEPTED
